
development:
  adapter: postgresql
  encoding: unicode
  database: iou_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: iou_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: iou_production
  pool: 5

